# Generated by Django 3.2.22 on 2023-10-31 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=255)),
                ('location', models.CharField(default='N/A', max_length=255)),
                ('experience', models.CharField(default='N/A', max_length=255)),
                ('type', models.CharField(default='Other', max_length=255)),
                ('rating', models.CharField(default='N/A', max_length=255)),
                ('image_url', models.URLField(default='https://example.com/default-image.jpg')),
            ],
        ),
        migrations.CreateModel(
            name='Advocatecatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.TextField(default='N/A')),
            ],
        ),
        migrations.CreateModel(
            name='Advocatecatagoryfin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Advocatefin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=255)),
                ('location', models.CharField(default='N/A', max_length=255)),
                ('experience', models.CharField(default='N/A', max_length=255)),
                ('type', models.CharField(default='other', max_length=255)),
                ('rating', models.CharField(default='N/A', max_length=255)),
                ('image_url', models.URLField(default='https://example.com/default-image.jpg')),
                ('practice_area_skills', models.TextField(default='Criminals & Consumer Court')),
            ],
        ),
        migrations.CreateModel(
            name='Aribitration_mediator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('practice_areas', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('contact_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eitheruserlawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Extradetaillawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(default='N/A', max_length=255)),
                ('contact', models.CharField(default='N/A', max_length=255)),
                ('country', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Laweruser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, default='lawer', editable=False, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('eitheruserlawyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.eitheruserlawyer')),
                ('extradetaillawer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.extradetaillawer')),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('catagory', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_detail_name', models.CharField(max_length=255)),
                ('user_detail_email', models.CharField(max_length=255)),
                ('type', models.CharField(default='user', editable=False, max_length=255)),
                ('user_detail_password', models.CharField(max_length=255)),
                ('eitheruserlawyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.eitheruserlawyer')),
            ],
        ),
        migrations.CreateModel(
            name='Typelawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default='Criminals laweyers')),
                ('laweruser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.laweruser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myprojectapp.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.AddField(
            model_name='laweruser',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.room'),
        ),
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='myprojectapp.extradetaillawer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='myprojectapp.lawyer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.user_detail')),
            ],
        ),
    ]
