# Generated by Django 4.2.5 on 2023-09-22 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0002_eitheruserlawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='laweruser',
            name='eitheruserlawyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.eitheruserlawyer'),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='eitheruserlawyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.eitheruserlawyer'),
        ),
        migrations.AlterField(
            model_name='laweruser',
            name='type',
            field=models.CharField(default='lawer', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='type',
            field=models.CharField(default='user', editable=False, max_length=100),
        ),
    ]
