# Generated by Django 4.2.5 on 2023-09-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0003_laweruser_eitheruserlawyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extradetaillawer',
            name='laweruser',
        ),
    ]
