# Generated by Django 4.2.5 on 2023-09-22 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0005_alter_extradetaillawer_catagory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laweruser',
            name='extradetaillawer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.extradetaillawer'),
        ),
    ]
