# Generated by Django 4.2.5 on 2023-09-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0007_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
    ]
