# Generated by Django 4.2.5 on 2023-09-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0008_remove_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='laweruser',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.room'),
        ),
    ]
