# Generated by Django 4.2.5 on 2023-09-23 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0009_laweruser_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='typelawer',
            name='laweruser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myprojectapp.laweruser'),
        ),
    ]
