# Generated by Django 4.2.5 on 2023-09-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0010_typelawer_laweruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Advocatecatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='typelawer',
            name='type',
            field=models.TextField(default='Criminals laweyers'),
        ),
    ]
