# Generated by Django 4.2.5 on 2023-09-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0012_alter_advocate_experience_alter_advocate_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocatecatagoryfin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Advocatefin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=255)),
                ('location', models.CharField(default='N/A', max_length=255)),
                ('experience', models.CharField(default='N/A', max_length=255)),
                ('type', models.CharField(default='other', max_length=100)),
                ('rating', models.CharField(default='N/A', max_length=100)),
                ('image_url', models.URLField(default='https://example.com/default-image.jpg')),
                ('practice_area_skills', models.TextField(default='Criminals & Consumer Court')),
            ],
        ),
    ]
