# Generated by Django 4.2.5 on 2023-09-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectapp', '0014_aribitration_mediator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aribitration_mediator',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
